services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: testbed_1
    volumes:
      - ./workspace:/workspace
      - ./src:/var/www/html 
      - ./smtpclient:/etc/ssmtp
    ports:
      - 3000:80
    tty: true

volumes:
  db_data: